### ISSUE TITLE
Put the task in a namespace

### ISSUE THREAD

**Issue by arichiardi** [andrewmed/tools#1]
Hey!

I was actually looking for something like this for boot, and usually you pack your [task](https://github.com/Lambda-X/boot-pack-source/blob/master/src/replumb/boot_pack_source.clj#L104) in a namespace, using the boot export as in [here](https://github.com/Lambda-X/boot-pack-source/blob/master/src/replumb/boot_pack_source.clj).

Thanks for this!

**Comment by andrewmed** [comment]
Fixed.
Thanks!

**Comment by arichiardi** [comment]
Ok I checked and I guess you can also rename the files so that a `require` can find it as well, in your case it would be `yourgroupname/boot_maven_interop.clj`, does it make sense?

**Comment by andrewmed** [comment]
Done. Originally it was for internal use and c&p (thats why no namespace, etc), now it is turning into  library :)
Thank you for comments
